<a href="https://colab.research.google.com/github/RichaTiwari14/BulgThought/blob/main/torch_id.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch as nn
a=torch.rand(2,3)
b=a
a[0][0]=1
print(b)
print(id(a)) # id() :to get the address of tensor
print(id(b))

#now since we can see that a and b both are pointing to the same address. thi is due to the assignment operator
#to avoid this and also to clone the tensor in another we can use clone()

b=a.clone()
id(b) #now the address of b is different from a
 #and now if we will modify a there will be no effect on b
#eg.
a[0][0]=0
print(a)
print(b)

tensor([[1.0000, 0.6500, 0.0921],
        [0.2368, 0.9066, 0.2386]])
139125861367248
139125861367248
tensor([[0.0000, 0.6500, 0.0921],
        [0.2368, 0.9066, 0.2386]])
tensor([[1.0000, 0.6500, 0.0921],
        [0.2368, 0.9066, 0.2386]])


In [ ]:
torch.cuda.is_available()

False